### ISSUE TITLE
schema.sql does not include the actual database schema

### ISSUE THREAD

**Issue by Nick-Mazuk** [emilpriver/geni#129]
The generated `./migrations/schema.sql` file does not represent the actual database schema. It does not include any of the created tables.

Here's a repo with the minimal reproduction: https://github.com/Nick-Mazuk/geni-schema-repro

Note: the database itself is still migrated.

## Repro steps

Run the following commands:

```bash
brew install geni
geni --version
# geni v1.0.9

export DATABASE_URL=sqlite://./database.sqlite
geni new create_users

# 04:31:59 [INFO] Generated ./migrations/1719635519_create_users.up.sql
# 04:31:59 [INFO] Generated ./migrations/1719635519_create_users.down.sql
# 04:31:59 [INFO] Success
```

Then add the following to the up.sql file:

```sql
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  email TEXT NOT NULL UNIQUE
);
```

And the following to the down.sql file:

```sql
DROP TABLE IF EXISTS users;
```

Lastly, run the migration:

```bash
geni up
# 04:33:23 [INFO] Running migration 1719635519
# 04:33:23 [INFO] Success
```

## Expected

The generated `./migrations/schema.sql` file include the `users` table and be something like the following:

```sql
CREATE TABLE schema_migrations (id VARCHAR(255) PRIMARY KEY);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  email TEXT NOT NULL UNIQUE
);
```

## Actual

The generated `./migrations/schema.sql` only includes the `schema_migrations` table:

```sql
CREATE TABLE schema_migrations (id VARCHAR(255) PRIMARY KEY)
```

**Comment by emilpriver** [comment]
Hey, Thank you for reporting. I'm on it :D

**Comment by emilpriver** [comment]
and thank you for spending time to create a really detailed issue!
