### ISSUE TITLE
Not compatible with libsql v0.6

### ISSUE THREAD

**Issue by sjunepark** [emilpriver/geni#189]
When using libsql [v0.6](https://docs.rs/libsql/latest/libsql/), I get the error below when trying to run migration scripts based on a database initialize with libsql.

```shell
thread 'test_utils::tests::db_source_migration_should_create_empty_companies_table' panicked at /Users/sejunpark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsql-0.5.0/src/local/database.rs:209:17:
assertion `left == right` failed: libsql was configured with an incorrect threading configuration and
                    the api is not safe to use. Please check that no multi-thread options have
                    been set. If nothing was configured then please open an issue at:
                    https://github.com/libsql/libsql
  left: 21
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Here's a [reproduced repo](https://github.com/sjunepark/geni-issue).
You can just run `just bin`.
I'm not sure what's not compatible, but I think the error will go away if geni uses libsql v0.6.

Haven't got the time to check it out myself.

**Comment by emilpriver** [comment]
> When using libsql [v0.6](https://docs.rs/libsql/latest/libsql/), I get the error below when trying to run migration scripts based on a database initialize with libsql.
> 
> ```shell
> thread 'test_utils::tests::db_source_migration_should_create_empty_companies_table' panicked at /Users/sejunpark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsql-0.5.0/src/local/database.rs:209:17:
> assertion `left == right` failed: libsql was configured with an incorrect threading configuration and
>                     the api is not safe to use. Please check that no multi-thread options have
>                     been set. If nothing was configured then please open an issue at:
>                     https://github.com/libsql/libsql
>   left: 21
>  right: 0
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> ```
> 
> Here's a [reproduced repo](https://github.com/sjunepark/geni-issue).
> You can just run `just bin`.
> I'm not sure what's not compatible, but I think the error will go away if geni uses libsql v0.6.
> 
> Haven't got the time to check it out myself.

Hey! Thank you for reporting. I haven't got the time to merge the libsql upgrade branch but will look into it

**Comment by sjunepark** [comment]
@emilpriver That was fast, works fine thanks 👍
