### ISSUE TITLE
LibSQL RANDOM ROWID panics

### ISSUE THREAD

**Issue by devpikachu** [emilpriver/geni#38]
Whilst trying to run migrations that contain a [`RANDOM ROWID`](https://github.com/tursodatabase/libsql/blob/6f67c65a4094c52baa57b0c091e0b2d9e02533d9/libsql-sqlite3/doc/libsql_extensions.md#random-rowid) statement, the main thread panics. This is due to an upstream bug that has been reported here: https://github.com/tursodatabase/libsql-client-rs/issues/67

**Comment by emilpriver** [comment]
Hello and sorry for responding so late and thank you for reporting. I guess the only thing I can do now is to be aware if they fix it in libsql-client-rs and update when it's fixed :D

**Comment by emilpriver** [comment]
Hey, I'm closing this issue. I have changed the libsql library from libsql-client-rs -> libsql as libsql-client-rs is not being developed anymore. Feel free to open the issue if this still happens to you! :D
