### ISSUE TITLE
Sqlite(libsql)  trigger syntax

### ISSUE THREAD

**Issue by kingwill101** [emilpriver/geni#48]
The following query fails when working with libsql

~/.cargo/bin/geni up
20:28:08 [INFO] Running migration 1704270280
20:28:08 [ERROR] Error from server: StreamResponseError { error: Error { message: "SQL string could not be parsed: unexpected end of input at (11, 22)" } }

```sql
CREATE table
    IF NOT EXISTS bookmarks
(
    id            integer not null
        constraint bookmarks_pk primary key,

    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (collection_id) REFERENCES collections (id)
);

CREATE TRIGGER IF NOT EXISTS update_bookmark_collection_updated_at
    AFTER
        UPDATE
    ON bookmarks
    FOR EACH ROW
BEGIN
    UPDATE bookmarks
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = OLD.id;

END;

```

**Comment by emilpriver** [comment]
Hello,
I don't think this is a issue with the implementation, more that the code is faulty. 
Can you verify that this is a issue with Geni and not your code? Feel free to open the issue again if so
