### ISSUE TITLE
Install via Brew failed

### ISSUE THREAD

**Issue by riipandi** [emilpriver/geni#62]
Hi, I had an issue when installing via brew. I have attached the issue below.

<img width="690" alt="image" src="https://github.com/emilpriver/geni/assets/921834/178ffa2e-8e29-4e92-be77-0956427e30ad">

**Comment by emilpriver** [comment]
Hello and thank you for reporting :D 
Seems as the version was missing from the formula. I have updated the versions in the formula, can you try again?

**Comment by riipandi** [comment]
Trying to install again, now I got different issue:

<img width="1364" alt="image" src="https://github.com/emilpriver/geni/assets/921834/5c890ba5-246f-45cb-8f54-3afa0ff7c8c1">

**Comment by emilpriver** [comment]
Got ya, I will check :) Do you have Cargo installed or pkgx?

**Comment by emilpriver** [comment]
I made some fixes, can you try again and open if you still get a issue?
I managed to install on my machine now
