### ISSUE TITLE
1.0.0 release for macos-arm64 is downloading as amd64

### ISSUE THREAD

**Issue by mpellegrini** [emilpriver/geni#63]
Tried downloading the arm64 binary for Mac, but it appears it is actually the same version as the amd64.

$ file geni-macos-arm64 
`geni-macos-arm64: Mach-O 64-bit executable x86_64`

$ file geni-macos-amd64 
`geni-macos-amd64: Mach-O 64-bit executable x86_64`

⦁⦁⦁ ls -la geni-macos-a*
```
-rw-r--r--@ 1 michael  staff  15261496 Mar  1 08:50 geni-macos-amd64
-rw-r--r--@ 1 michael  staff  15261464 Mar  1 08:50 geni-macos-arm64
```

**Comment by emilpriver** [comment]
Hey, thank you for reporting. I will have a look ☺️

**Comment by emilpriver** [comment]
Hey,

Seems as the CI have ARM for building mac and rust compiler fallbacks to ARM target when building.

Can you use cargo ( `cargo install geni`) or Homebrew (`brew install emilpriver/geni/geni`) instead?

**Comment by emilpriver** [comment]
I am closing this as I added targets for mac builds. Please re-open if the issue still exist.

**Comment by mpellegrini** [comment]
Not a homebrew user but will try installing via cargo.  Thanks for looking into this.

**Comment by emilpriver** [comment]
Do it :) It's way easier for you as a consumer of the cli with using cargo as it get compiled into the target fitting your machine
