### ISSUE TITLE
Optimize build to only import the libraries needed

### ISSUE THREAD

**Issue by doroved** [emilpriver/geni#76]
You might consider specifying the desired database in features if it would have a positive impact on the size of our application at compile time.

**Comment by emilpriver** [comment]
Hello,

I am adding more context to this. I got the request to be able to programmatically run migrations. This is possible atm but it's not optimal as you get so many packages you don't need if you for instance only want to be able to make migrations for LibSQL. 

Action points for this is:
- [ ] Add database driver-specific libraries. We don't need SQLX if we want to make migrations for LibSQL
- [ ] Add public functions to each driver to be able to make migrations via code

**Comment by emilpriver** [comment]
I've have added this to my todo but I don't know when I will be able to achieve this ☺️

**Comment by emilpriver** [comment]
Geni was built to be a CLI so we're sticking with it.
