### ISSUE TITLE
Support for embed migrations

### ISSUE THREAD

**Issue by doroved** [emilpriver/geni#78]
There is a lack of support for built-in migrations.

**Example:**
https://docs.diesel.rs/master/diesel_migrations/macro.embed_migrations.html

**Comment by emilpriver** [comment]
Embed migrations seems nice ☺️ I add it in the same time I work on !76

**Comment by emilpriver** [comment]
Btw, PR's are welcome ofc :)

**Comment by emilpriver** [comment]
Geni was built to be a CLI and not to be something integrated within production apps. Better to use something built for be running in prod rather then geni
